services:
  SaaSFormation\Framework\MessageBus\Infrastructure\TacticianCommandBusLogFormatter:

  SaaSFormation\Framework\MessageBus\Infrastructure\TacticianQueryBusLogFormatter:

  SaaSFormation\Framework\MessageBus\Infrastructure\TacticianEventBusLogFormatter:

  tactician_commandbus_logger_middleware:
    class: League\Tactician\Logger\LoggerMiddleware
    arguments:
      $formatter: '@SaaSFormation\Framework\MessageBus\Infrastructure\TacticianCommandBusLogFormatter'
      $logger: '@default_logger'

  tactician_querybus_logger_middleware:
    class: League\Tactician\Logger\LoggerMiddleware
    arguments:
      $formatter: '@SaaSFormation\Framework\MessageBus\Infrastructure\TacticianQueryBusLogFormatter'
      $logger: '@default_logger'

  SaaSFormation\Framework\MessageBus\Infrastructure\TacticianBasedQueryBusHandlerNameInflector:

  League\Tactician\Handler\MethodNameInflector\HandleInflector:

  League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor:

  SaaSFormation\Framework\MessageBus\Infrastructure\TacticianCommandBusInterfaceBasedHandlerLocator:
    arguments:
      $container: '@service_container'
      $logger: '@default_logger'

  SaaSFormation\Framework\MessageBus\Infrastructure\TacticianQueryBusInterfaceBasedHandlerLocator:
    arguments:
      $container: '@service_container'
      $logger: '@default_logger'

  SaaSFormation\Framework\Projects\Infrastructure\EventDispatcher\EventDispatcher:
    arguments:
      $container: '@service_container'
      $logger: '@default_logger'

  SaaSFormation\Framework\MessageBus\Infrastructure\CommandBusSendEventsToEventStreamMiddleware:
    arguments:
      $eventDispatcher: '@SaaSFormation\Framework\Projects\Infrastructure\EventDispatcher\EventDispatcher'
      $commandNameExtractor: '@League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor'
      $handlerLocator: '@SaaSFormation\Framework\MessageBus\Infrastructure\TacticianCommandBusInterfaceBasedHandlerLocator'
      $methodNameInflector: '@League\Tactician\Handler\MethodNameInflector\HandleInflector'
      $repository: '@SaaSFormation\Framework\SharedKernel\Domain\WriteModel\RepositoryInterface'
      $UUIDFactory: '@SaaSFormation\Framework\SharedKernel\Common\Identity\UUIDFactoryInterface'
      $mongoDBClientProvider: '@SaaSFormation\Framework\MongoDBBasedReadModel\Infrastructure\ReadModel\MongoDBClientProvider'

  tactician_querybus_query_handler_middleware:
    class: League\Tactician\Handler\CommandHandlerMiddleware
    arguments:
      $commandNameExtractor: '@League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor'
      $handlerLocator: '@SaaSFormation\Framework\MessageBus\Infrastructure\TacticianQueryBusInterfaceBasedHandlerLocator'
      $methodNameInflector: '@SaaSFormation\Framework\MessageBus\Infrastructure\TacticianBasedQueryBusHandlerNameInflector'

  tactician_command_bus:
    class: League\Tactician\CommandBus
    arguments:
      -
        - '@tactician_commandbus_logger_middleware'
        - '@SaaSFormation\Framework\MessageBus\Infrastructure\CommandBusSendEventsToEventStreamMiddleware'

  tactician_query_bus:
    class: League\Tactician\CommandBus
    arguments:
      -
        - '@tactician_querybus_logger_middleware'
        - '@tactician_querybus_query_handler_middleware'

  SaaSFormation\Framework\MessageBus\Infrastructure\TacticianBasedCommandBus:
    arguments:
      - '@tactician_command_bus'

  SaaSFormation\Framework\MessageBus\Infrastructure\TacticianBasedQueryBus:
    arguments:
      - '@tactician_query_bus'

  SaaSFormation\Framework\Projects\UI\API\HTTP\ReactPHPBasedJSONResponder:

  SaaSFormation\ArrayByPath\RetrieveArrayValueByPathService:

  SaaSFormation\Framework\Projects\UI\API\HTTP\AbstractEndpoint:
    public: true
    arguments:
      $defaultResponseContentType: "application/json"
      $logger: '@default_logger'
      $commandBus: '@SaaSFormation\Framework\MessageBus\Infrastructure\TacticianBasedCommandBus'
      $queryBus: '@SaaSFormation\Framework\MessageBus\Infrastructure\TacticianBasedQueryBus'
      $retrieveArrayValueByPathService: '@SaaSFormation\ArrayByPath\RetrieveArrayValueByPathService'
      $responders:
        application/json: '@SaaSFormation\Framework\Projects\UI\API\HTTP\ReactPHPBasedJSONResponder'

  SaaSFormation\Framework\Projects\Infrastructure\Identity\RamseyBasedUUIDFactory:

  SaaSFormation\Framework\MessageBus\Application\CommandBusInterface:
    public: true
    alias: 'SaaSFormation\Framework\MessageBus\Infrastructure\TacticianBasedCommandBus'
  SaaSFormation\Framework\MessageBus\Application\QueryBusInterface:
    public: true
    alias: 'SaaSFormation\Framework\MessageBus\Infrastructure\TacticianBasedQueryBus'
  SaaSFormation\Framework\SharedKernel\Common\Identity\UUIDFactoryInterface:
    alias: 'SaaSFormation\Framework\Projects\Infrastructure\Identity\RamseyBasedUUIDFactory'
    public: true