services:
  SaaSFormation\Framework\Projects\Infrastructure\ReadModel\MongoDBClientProvider:
    public: true
    arguments:
      $envVarsManager: '@default_env_vars_manager'

  SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianCommandBusLogFormatter:

  SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianQueryBusLogFormatter:

  SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianEventBusLogFormatter:

  tactician_commandbus_logger_middleware:
    class: League\Tactician\Logger\LoggerMiddleware
    arguments:
      $formatter: '@SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianCommandBusLogFormatter'
      $logger: '@default_logger'

  tactician_querybus_logger_middleware:
    class: League\Tactician\Logger\LoggerMiddleware
    arguments:
      $formatter: '@SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianQueryBusLogFormatter'
      $logger: '@default_logger'

  SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianBasedQueryBusHandlerNameInflector:

  League\Tactician\Handler\MethodNameInflector\HandleInflector:

  League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor:

  SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianCommandBusInterfaceBasedHandlerLocator:
    arguments:
      $container: '@service_container'
      $logger: '@default_logger'

  SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianQueryBusInterfaceBasedHandlerLocator:
    arguments:
      $container: '@service_container'
      $logger: '@default_logger'

  SaaSFormation\Framework\Projects\Infrastructure\EventDispatcher\EventDispatcher:
    arguments:
      $container: '@service_container'
      $logger: '@default_logger'

  SaaSFormation\Framework\Projects\Infrastructure\Bus\CommandBusSendEventsToEventStreamMiddleware:
    arguments:
      $eventDispatcher: '@SaaSFormation\Framework\Projects\Infrastructure\EventDispatcher\EventDispatcher'
      $commandNameExtractor: '@League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor'
      $handlerLocator: '@SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianCommandBusInterfaceBasedHandlerLocator'
      $methodNameInflector: '@League\Tactician\Handler\MethodNameInflector\HandleInflector'

  tactician_querybus_query_handler_middleware:
    class: League\Tactician\Handler\CommandHandlerMiddleware
    arguments:
      $commandNameExtractor: '@League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor'
      $handlerLocator: '@SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianQueryBusInterfaceBasedHandlerLocator'
      $methodNameInflector: '@SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianBasedQueryBusHandlerNameInflector'

  tactician_command_bus:
    class: League\Tactician\CommandBus
    arguments:
      -
        - '@tactician_commandbus_logger_middleware'
        - '@SaaSFormation\Framework\Projects\Infrastructure\Bus\CommandBusSendEventsToEventStreamMiddleware'

  tactician_query_bus:
    class: League\Tactician\CommandBus
    arguments:
      -
        - '@tactician_querybus_logger_middleware'
        - '@tactician_querybus_query_handler_middleware'

  SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianBasedCommandBus:
    arguments:
      - '@tactician_command_bus'

  SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianBasedQueryBus:
    arguments:
      - '@tactician_query_bus'

  SaaSFormation\Framework\Projects\UI\API\HTTP\ReactPHPBasedJSONResponder:

  SaaSFormation\ArrayByPath\RetrieveArrayValueByPathService:

  SaaSFormation\Framework\Projects\UI\API\HTTP\Endpoint:
    public: true
    arguments:
      $defaultResponseContentType: "application/json"
      $logger: '@default_logger'
      $commandBus: '@SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianBasedCommandBus'
      $queryBus: '@SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianBasedQueryBus'
      $retrieveArrayValueByPathService: '@SaaSFormation\ArrayByPath\RetrieveArrayValueByPathService'
      $responders:
        application/json: '@SaaSFormation\Framework\Projects\UI\API\HTTP\ReactPHPBasedJSONResponder'

  SaaSFormation\Framework\Projects\Infrastructure\Identity\RamseyBasedUUIDFactory:

  SaaSFormation\Framework\Projects\Infrastructure\ReadModel\MongoDBBasedReadModelRepository:
    arguments:
      $mongoDBClientProvider: '@SaaSFormation\Framework\Projects\Infrastructure\ReadModel\MongoDBClientProvider'
      $logger: '@default_logger'

  SaaSFormation\Framework\Contracts\Application\Bus\CommandBusInterface:
    public: true
    alias: 'SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianBasedCommandBus'
  SaaSFormation\Framework\Contracts\Application\Bus\QueryBusInterface:
    public: true
    alias: 'SaaSFormation\Framework\Projects\Infrastructure\Bus\TacticianBasedQueryBus'
  SaaSFormation\Framework\Contracts\Common\Identity\UUIDFactoryInterface:
    alias: 'SaaSFormation\Framework\Projects\Infrastructure\Identity\RamseyBasedUUIDFactory'
    public: true